apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-health-check-uc1x
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-txjs-tenant/e2e-nodejs/nodejs-health-check-uc1x@sha256:5f11f1c986dad01a7c1de36d341fd90a7e16ee076bb5bd4262981f2af17407d1
        name: my-nodejs
        resources: {}
status: {}
